services:
  - type: web
    name: neurox_webhook_bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: API_TOKEN
        sync: false
